### ISSUE TITLE
Layout is not working

### ISSUE THREAD

**Issue by hunbarna72** [enginkirmaci/SnapIt#20]
I installed the program on an HP EliteBook x360 1030 G2 x64 (Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz   2.71 GHz). Unfortunately, the machine can only run the Windows 10 Pro 22H2 19045.3803 operating system, the 11 is not compatible with the device. I installed this application to be able to properly position windows exposed to an ultra-wide screen. Unfortunately, I find that this feature is completely inactive. I cannot even open the Layout tab.

**Comment by enginkirmaci** [comment]
Hi there,
When you install the SnapIt application using the installer available on GitHub, it creates a folder for logs under C:\Users\<username>\AppData\Local\SnapIt\logs here. Could you please post the logs here?

**Comment by Ghost-Girls** [comment]
> I installed the program on an HP EliteBook x360 1030 G2 x64 (Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz 2.71 GHz). Unfortunately, the machine can only run the Windows 10 Pro 22H2 19045.3803 operating system, the 11 is not compatible with the device. I installed this application to be able to properly position windows exposed to an ultra-wide screen. Unfortunately, I find that this feature is completely inactive. I cannot even open the Layout tab.

You can log out of your account or restart your computer, and the Layout tab is ready to use. This is what happens with this.exe installation version.

**Comment by hunbarna72** [comment]
There is no folder with this name in the specified location. The other is that logging out doesn't work because there is nowhere to log out from, restarting windows doesn't work because I tried. I think the problem is that I installed from the Microsoft Store, not the traditional way... :/
Where could this be achieved with a traditional installer?

**Comment by hunbarna72** [comment]
![Képernyőkép 2024-01-04 215901](https://github.com/enginkirmaci/SnapIt/assets/155262351/b73e8911-7bf4-4aeb-843a-cad28f336c38)

**Comment by hunbarna72** [comment]
![Képernyőkép 2024-01-04 215952](https://github.com/enginkirmaci/SnapIt/assets/155262351/9ceb3dd6-d7f0-44bc-851f-02cbbeae1a36)

**Comment by enginkirmaci** [comment]
Here you go, 
https://github.com/enginkirmaci/SnapIt/releases/download/5.0.5.0/setup_SnapIt_5.0.5.0.exe

**Comment by hunbarna72** [comment]
[log20240105_001.txt](https://github.com/enginkirmaci/SnapIt/files/13846620/log20240105_001.txt)
[log20240105_002.txt](https://github.com/enginkirmaci/SnapIt/files/13846621/log20240105_002.txt)
[log20240105_003.txt](https://github.com/enginkirmaci/SnapIt/files/13846622/log20240105_003.txt)
[log20240105_004.txt](https://github.com/enginkirmaci/SnapIt/files/13846623/log20240105_004.txt)
[log20240105_005.txt](https://github.com/enginkirmaci/SnapIt/files/13846624/log20240105_005.txt)
[log20240105_006.txt](https://github.com/enginkirmaci/SnapIt/files/13846625/log20240105_006.txt)
[log20240105_007.txt](https://github.com/enginkirmaci/SnapIt/files/13846626/log20240105_007.txt)
[log20240105_008.txt](https://github.com/enginkirmaci/SnapIt/files/13846627/log20240105_008.txt)
[log20240105_009.txt](https://github.com/enginkirmaci/SnapIt/files/13846628/log20240105_009.txt)
[log20240105_010.txt](https://github.com/enginkirmaci/SnapIt/files/13846629/log20240105_010.txt)
[log20240105.txt](https://github.com/enginkirmaci/SnapIt/files/13846630/log20240105.txt)

**Comment by hunbarna72** [comment]
Thanks, I tried to install it that way. Unfortunately it still doesn't work, but at least I have the folder you asked for.

**Comment by hunbarna72** [comment]
[log20240105.txt](https://github.com/enginkirmaci/SnapIt/files/13846652/log20240105.txt)
[log20240105_001.txt](https://github.com/enginkirmaci/SnapIt/files/13846653/log20240105_001.txt)
[log20240105_002.txt](https://github.com/enginkirmaci/SnapIt/files/13846654/log20240105_002.txt)
[log20240105_003.txt](https://github.com/enginkirmaci/SnapIt/files/13846655/log20240105_003.txt)
[log20240105_004.txt](https://github.com/enginkirmaci/SnapIt/files/13846656/log20240105_004.txt)
[log20240105_005.txt](https://github.com/enginkirmaci/SnapIt/files/13846657/log20240105_005.txt)
[log20240105_006.txt](https://github.com/enginkirmaci/SnapIt/files/13846658/log20240105_006.txt)
[log20240105_007.txt](https://github.com/enginkirmaci/SnapIt/files/13846660/log20240105_007.txt)
[log20240105_008.txt](https://github.com/enginkirmaci/SnapIt/files/13846661/log20240105_008.txt)
[log20240105_009.txt](https://github.com/enginkirmaci/SnapIt/files/13846662/log20240105_009.txt)
[log20240105_010.txt](https://github.com/enginkirmaci/SnapIt/files/13846663/log20240105_010.txt)

**Comment by enginkirmaci** [comment]
I suspect you edit one of the layout manually by opening json file. But coordinates can only be integer. The error is '511.2'. So to fix this, modify layout that has decimal numbers or delete all layouts in folder.
There is also one more error in settings.json, you can also remove it. 
In the meantime, I'll look what can I do to solve both problem.
