### ISSUE TITLE
Excluding Apps not working

### ISSUE THREAD

**Issue by ivan8994** [enginkirmaci/SnapIt#21]
**Describe the bug**
when you need any app to be excluded from snapping, you can add this app in the options menu. The problem is, you cant add any app there

**To Reproduce**
open settings
1. Go to menu Window
2. see Excluded Applications and press New
3. choose app from list of existing or enter title into the Keyword field
4. when you pick the app, the list of excluded apps just gest a new line with empty fiend, no title of the app, no any information, and the app that you think you added still reacts to tiling

**Expected behavior**
when you select the app from the list, it becomes listed in the menu, abd becomes unresponsible to snapping
instead, nothing happens

**Screenshots**
![Screenshot (841)](https://github.com/enginkirmaci/SnapIt/assets/75372078/b960c6a0-7670-4eac-882f-1e87f6e9522f)

**Comment by enginkirmaci** [comment]
Thanks for reporting,
It'll be fixed with version 5.0.6
